version: '3.9'

services:
  frontend:
    build: ./frontend-service
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - order-service

  user-service:
    build: ./user-service
    ports:
      - "8080:8080"

  order-service:
    build: ./order-service
    ports:
      - "5000:5000"

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs

  jenkins:
    build:
      context: ./custom-dockerfiles
      dockerfile: jenkins.Dockerfile
    # image: jenkins/jenkins:lts-jdk17
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    networks:
      - default
      - kind

volumes:
  jenkins_home:
  sonar_data:
  sonar_extensions:
  sonar_logs:

networks:
  default:
  kind:
    external: true
